- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
    - name: Copy join command from master
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
      fetch:
        src: /tmp/kubeadm_join.sh
        dest: /tmp/kubeadm_join.sh
        flat: yes

    - name: Join cluster
      command: sh /tmp/kubeadm_join.sh